# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7a8268b1befef0b457cad052d6f01de9bc07a4d81994458ab09a00fa399e5c8c761c0b1edae6669f0312b6c6d81fc40b04ba07c890646de2c0dbd202e839170

test:
  secret_key_base: 5446ce1ce78b2000bfc4e56ffeac132b0c6e5c83151b5101f5c7cd3e18a1b549da7efcc02102e6753c579fd72d528149a6eecd0336f3fce2841e20d08c44ca12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: "165e3469f74b42faa769f7b00f9f309ccd88eca8e4d1d01a47dfa6d7bfa9bbb9f7be6fb71832988a208ed90bc3b51b8aeee2fc2a459a2d607b5fadbf0f743ebd"
